// src/app/registeredUser/feed/feed.component.ts
import { Component } from '@angular/core';
import { DashboardModule } from '../sideNav/sideNav.module';
import { OnInit } from '@angular/core';
import { placementsData } from '../placements/placements-data';
import { CommonModule } from '@angular/common';
import { soundPacksData } from '../sound-packs/soundPacks-data';
import { servicesData } from '../servicios/services-data';

@Component({
  selector: 'app-feed',
  standalone: true,
  imports: [DashboardModule, CommonModule],
  templateUrl: './feed.component.html',
  styleUrl: './feed.component.css'
})
export class FeedComponent {


  images: string[] = ['/assets/dashboard/beatstarsLogo.webp', '/assets/dashboard/discordLogo.webp', '/assets/main/googlePlayImage.webp']; 
  currentImageIndex = 0;

  placements = placementsData;
  soundPacks = soundPacksData;
  services = servicesData;
  

  get currentImage(): string {
    return this.images[this.currentImageIndex];
  }

  showNextImage(): void {
    this.currentImageIndex = (this.currentImageIndex + 1) % this.images.length;

  }

  showPreviousImage(): void {
    this.currentImageIndex = (this.currentImageIndex - 1 + this.images.length) % this.images.length;

  }


}

<section class="min-h-screen bg-[url('/assets/dashboard/BACKGROUND.webp')] w-full h-full bg-no-repeat bg-cover text-white ">
  <app-sideNav></app-sideNav>

<div class="container">
  <!--
    <div class="">
    <button class='w-16' (click)="showPreviousImage()">
      <img style="transform: rotate(180deg);" class="imageArrow" src="/assets/feed/arrowLogo.webp"
        alt="Imagen actual" />
    </button>

    <img class="image z-1 pb-5 w-full md:w-2/3" [src]="currentImage" alt="Imagen actual" />

    <button class='w-16' (click)="showNextImage()">
      <img class="imageArrow" src="/assets/feed/arrowLogo.webp" alt="Imagen actual" />
    </button>
  </div>


  https://www.youtube.com/watch?v=ywLgqJjLUm4 BACKGROUND
  -->
  

  <div id="default-carousel" class="relative w-full">

    <div class="relative h-56 overflow-hidden rounded-lg md:h-96 z-1">

        <div class="duration-700 ease-in-out z-1" data-carousel-item>
            <img [src]="currentImage" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
        </div>
    </div>
 
    <div class="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
        <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 4" data-carousel-slide-to="3"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 5" data-carousel-slide-to="4"></button>
    </div>

    <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" (click)="showPreviousImage()" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
            </svg>
            <span class="sr-only">Previous</span>
        </span>
    </button>
    <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" (click)="showNextImage()" data-carousel-next>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="sr-only">Next</span>
        </span>
    </button>

</div>

  <div class="options">
    <button type="button" class="optionButton" [routerLink]="['/profile']"><p class="textOption z-10 font-bold">Mi Perfil</p></button>
    <button type="button" class="optionButton" [routerLink]="['/trackLibrary']"><p class="textOption font-bold">Mis mp3</p></button>
    <button type="button" class="optionButton" [routerLink]="['/purchases']"><p class="textOption font-bold">Mis compras</p></button>
  </div>

  <div class="placements">
    <h3 class="text-xl">Placements</h3>

    <div class="description">
      <p  class="pb-3">Descripcion de lo que es un placement....</p>

      <div class="navigate">
        <p class="navigate-element">⬅️</p>
        <p class="navigate-element">➡️</p>
        <button type="button" [routerLink]="['/placements']"><p class="showAll">Ver Todos</p></button>
      </div>

    </div>


    <li class="placements-data" *ngFor="let data of placements">
      <div class="placementContainer">

        <img class="placementImage" [src]="[data.srcPhoto]" alt="placementImage">
        <div class="placement-info">
          <p class="typeOfPlacement">{{data.placementsType}}</p>
          <h5 class="nameOfPlacement">{{data.placementName}}</h5>
          <h6 class="discography">{{data.discography}}</h6>
          <p class="timeLeft">{{data.timeLeft}}</p>
        </div>

      </div>

    </li>
  </div>


  <div class="soundPacks">
    <h3 class="text-xl">SoundPacks, Drumkits, etc.</h3>

    <div class="description">
      <p class="pb-3">Descripcion.....</p>

      <div class="navigate">
        <p class="navigate-element">⬅️</p>
        <p class="navigate-element">➡️</p>
        <button type="button" [routerLink]="['/marketPlace']"><p class="showAll">Ver Todos</p></button>
      </div>
    </div>
    

    <li class="soundPacksData" *ngFor="let data of soundPacks">
      
      <div class="soundPackCointainer">
        <img [src]="[data.srcPhoto]" alt="soundPackImage" class="soundPackImage">
        <div class="soundPack-info">
          <h6>{{data.name}}</h6>
          <button type='button' class="downloadButton">Download</button>
        </div>
        
      </div>
    </li>

  </div>


  <div class="servicios">
    <h3 class="text-xl">Servicios</h3>

    <p class="pb-3">Podras contar con cursos en diversas areas de la produccion o cualquier otra forma de contacto con la escena musical...</p>

    <li class="services-data" *ngFor="let data of services">

      <div class="serviceContainer">
        <img [src]="[data.srcPhoto]" alt="imageService" class="services-image">

        <div class="serviceInfo">
          <h6 class="serviceName">{{data.name}}</h6>
          <p class="serviceDescription">{{data.description}}</p>
        </div>
        
        <button type="button" class="buyButton">Comprar</button>
      </div>
    </li>
  </div>

</div>
</section>

// app/routes/feed.tsx
import { useAuth0 } from "@auth0/auth0-react";
import SideNav from "~/components/sideNav";

export default function Index() {
  const { user } = useAuth0();

  return (
    <section className="min-h-screen w-full h-full bg-gradient-to-b from-black via-purple-900 to-black text-white ">
      <SideNav />

      <div className="ml-80">
        <h1 className="pr-4 py-4 w-full text-3xl font-semibold">Feed</h1>

        <div
          id="default-carousel"
          className="relative w-full flex justify-center mb-5"
        >
          <div className="relative h-56 overflow-hidden rounded-3xl md:h-96 z-1 border w-11/12 items-center">
            <div className="duration-700 ease-in-out z-1" data-carousel-item>
              <img
                src="discordLogo.webp"
                className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 "
                alt="..."
              />
            </div>
          </div>

          <button
            type="button"
            className="absolute top-0 start-0 z-30 flex items-center justify-center h-full pl-32 group"
            data-carousel-prev
          >
            <span className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30  dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
              <svg
                className="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 6 10"
              >
                <path stroke="currentColor" d="M5 1 1 5l4 4" />
              </svg>
              <span className="sr-only">Previous</span>
            </span>
          </button>

          <button
            type="button"
            className="absolute top-0 end-0 z-30 flex items-center justify-center h-full pr-32  group"
            data-carousel-next
          >
            <span className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
              <svg
                className="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 6 10"
              >
                <path stroke="currentColor" d="m1 9 4-4-4-4" />
              </svg>
              <span className="sr-only">Next</span>
            </span>
          </button>
        </div>

        <div className="grid grid-cols-3 gap-3 justify-center rounded-lg backdrop-blur-md py-4 my-3 mr-5">
          {["Mi Perfil", "Mis MP3", "Mis compras"].map((title, index) => (
            <button
              key={index}
              type="button"
              className="pl-6 pr-40 py-6 bg-white/10 hover:bg-gradient-to-r hover:from-purple-600 hover:to-purple-950 text-white rounded-lg transition-all duration-300 text-left shadow-md"
            >
              <p className="font-bold mb-1">{title}</p>
              <p className="text-sm">
                {title === "Mi Perfil"
                  ? `¡Bienvenido a HypeSounds ${user?.name}, entra a ver los datos de tu perfil!`
                  : title === "Mis MP3"
                  ? "Comparte y administra tu musica"
                  : "Administra tus compras"}
              </p>
            </button>
          ))}
        </div>

        <div className="placements my-10">
          <h1 className="w-full text-3xl font-semibold">Placements</h1>
          <div className="grid grid-cols-2 gap-2">
            <p className="pb-3 text-sm">
              HypeSounds© optimiza tu flujo de trabajo y te brinda acceso
              instantáneo a oportunidades de colocación con los principales
              artistas y sellos discográficos.
            </p>

            <div className="flex justify-end pr-5 space-x-3">
              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full ">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="M5 1 1 5l4 4" />
                  </svg>
                </span>
              </button>

              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="m1 9 4-4-4-4" />
                  </svg>
                </span>
              </button>

              <button type="button">
                <p className="px-5 hover:underline"> Ver Todos</p>
              </button>
            </div>
          </div>

          <li className="placements-data">
            <div className="placementContainer">
              <img className="placementImage" alt="placementImage" />
              <div className="placement-info">
                <p className="typeOfPlacement"></p>
                <p className="nameOfPlacement"></p>
                <p className="discography"></p>
                <p className="timeLeft"></p>
              </div>
            </div>
          </li>
        </div>

        <div className="SoundPacksEtc my-10">
          <h1 className="w-full text-3xl font-semibold">
            SoundPacks, Drumkits, etc.
          </h1>
          <div className="grid grid-cols-2 gap-2">
            <p className="pb-3 text-sm">
              Explora nuestra biblioteca de sonidos, que incluye opciones tanto
              libres de derechos y con derechos de autor, seleccionadas y
              producidas por nuestro reconocido productor GrowBeatz.
            </p>

            <div className="flex justify-end pr-5 space-x-3">
              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="M5 1 1 5l4 4" />
                  </svg>
                </span>
              </button>

              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="m1 9 4-4-4-4" />
                  </svg>
                </span>
              </button>

              <button type="button">
                <p className="px-5 hover:underline"> Ver Todos</p>
              </button>
            </div>
          </div>

          <li className="soundPacksData">
            <div className="soundPackCointainer">
              <img alt="soundPackImage" className="soundPackImage" />
              <div className="soundPack-info">
                <p></p>
                <button type="button" className="bg-red-950">
                  Download
                </button>
              </div>
            </div>
          </li>
        </div>

        <div className="servicios my-10">
          <h3 className="w-full text-3xl font-semibold">Servicios</h3>

          <div className="grid grid-cols-2 gap-2">
            <p className="pb-3 text-sm">
              Accede a cursos especializados en diversas áreas de la producción
              musical y descubre nuevas formas de conectar con la industria.
            </p>

            <div className="flex justify-end pr-5 space-x-3">
              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="M5 1 1 5l4 4" />
                  </svg>
                </span>
              </button>

              <button className="transition-transform transform hover:scale-150">
                <span className="inline-flex items-center justify-center w-10 h-10 rounded-full">
                  <svg
                    className="w-4 h-4 text-white dark:text-white rtl:rotate-180"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 6 10"
                  >
                    <path stroke="currentColor" d="m1 9 4-4-4-4" />
                  </svg>
                </span>
              </button>

              <button type="button">
                <p className="px-5 hover:underline"> Ver Todos</p>
              </button>
            </div>
          </div>

          <li className="services-data">
            <div className="serviceContainer">
              <img alt="imageService" className="services-image" />

              <div className="serviceInfo">
                <p className="serviceName"></p>
                <p className="serviceDescription"></p>
              </div>

              <button type="button" className="bg-red-950">
                Comprar
              </button>
            </div>
          </li>
        </div>
      </div>
    </section>
  );
}
