// app/components/sideNav.tsx
import { useAuth0 } from "@auth0/auth0-react";

const SideNav = () => {
  const { user, logout, isLoading } = useAuth0();

  const truncateText = (text: string, maxLength: number) => {
    if (text.length > maxLength) {
      return text.substring(0, maxLength) + "...";
    } else {
      return text;
    }
  };

  return (
    <nav className="fixed left-0 top-0 w-72 h-screen bg-black text-white p-6 flex flex-col justify-between shadow-xl border-r border-purple-500">
      <div className="mb-6">
        <h2 className="text-4xl font-bold text-center text-[#FB4FEF] drop-shadow-lg">
          HypeSounds©
        </h2>
      </div>

      <div className="flex items-center space-x-2 bg-[#1a1a1a] p-4 rounded-lg shadow-lg border border-[#FB4FEF]">
        {!isLoading ? (
          <div className="flex space-x-2">
            <img
              src="/logo.webp"
              alt={user?.name || "User Avatar"}
              className="w-12 h-12 rounded-full hover:scale-110 transition-transform duration-300"
            />
            <div className="flex flex-col">
              <p className="font-bold text-lg text-[#FB4FEF]">
                {user?.name ? truncateText(user?.name, 12) : ""}
              </p>
              <p className="text-gray-400 text-sm">
                {user?.email ? truncateText(user?.email, 16) : ""}
              </p>
            </div>
          </div>
        ) : (
          <p>LOADING ...</p>
        )}
      </div>

      <div className="mt-6 space-y-2 flex-1">
        <h6 className="text-[#FB4FEF] uppercase text-sm">Main</h6>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Feed
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Placements
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Market Place
        </button>

        <h6 className="text-[#FB4FEF] uppercase text-sm mt-4">Profile</h6>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Profile
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Mis mp3
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Mis compras
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Historial
        </button>

        <h6 className="text-[#FB4FEF] uppercase text-sm mt-4">Más...</h6>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Resources
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Configuración
        </button>
        <button className="w-full bg-[#2a2a2a] hover:bg-[#FB4FEF] py-1.5 rounded-md text-left pl-4 transition-all">
          Support
        </button>
        <button
          className="w-full bg-red-600 hover:bg-red-500 py-1.5 rounded-md text-left pl-4 transition-all"
          onClick={() => logout()}
        >
          Cerrar Sesión
        </button>
      </div>

      <div className="mt-6 grid grid-cols-4 gap-2">
        <img className="h-10" src="/youtubeLogo.webp" alt="YouTube" />
        <img className="h-10" src="/instagramLogo.webp" alt="Instagram" />
        <img className="h-10" src="/discordLogo.webp" alt="Discord" />
        <img className="h-10" src="/beatstarsLogo.webp" alt="BeatStars" />
      </div>

      <div className="text-center text-gray-500 text-sm mt-6">
        <p>© 2023 Hype Sounds.</p>
        <p>All rights reserved.</p>
      </div>
    </nav>
  );
};

export default SideNav;

// src/app/registeredUser/sideNav/sideNav.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, ChangeDetectionStrategy, Component } from '@angular/core';
import { Router, RouterLink, RouterOutlet } from '@angular/router';
import { AuthService } from '@auth0/auth0-angular';

@Component({
  selector: 'app-sideNav',
  standalone: true,
  imports: [CommonModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './sideNav.component.html',
  styleUrl: './sideNav.component.css'
})
export class sideNavComponent {

  constructor(private auth : AuthService, private router : Router, private cdr: ChangeDetectorRef) {}

  getUserInfo() {
    return this.auth.user$;
  }

  currentSection: string = '';
  activeButton: string = 'feed';

  changeSection(section: string) {
    this.currentSection = section;
    this.router.navigateByUrl(`/${section}`)
    this.cdr.detectChanges();

  }

  isButtonActive(button: string): boolean {
    return this.activeButton === button;
  }

  logout(){
    this.auth.logout();
  }

  truncateText(text: string, maxLength: number): string {
    if (text.length > maxLength) {
      return text.substring(0, maxLength) + '...';
    } else {
      return text;
    }
  }
}

<nav class="classForbackground text-white">

  <div class="container">
    <h2 class="title text-3xl">HypeSounds©</h2>

    <div class="userData" *ngIf="getUserInfo() | async as user">
        <img *ngIf="user.picture" [src]="user.picture" alt="User Avatar">
        <div class="userDetails">
          <p class="userName">{{ user.name ? truncateText(user.name, 17) : '' }}</p>
          <p>{{ user.email ? truncateText(user.email, 17) : '' }}</p>
        </div>
        
        
    </div>

    

    <div class="sideNav">
        <h6 class="mb-2">MAIN</h6>

        <button (click)="changeSection('feed')" [ngClass]="{'active': currentSection === 'feed'}">Feed</button>
        <br>
        <button (click)="changeSection('placements')" [ngClass]="{'active': currentSection === 'placements'}">Placements</button>
        <br>
        <button (click)="changeSection('marketPlace')" [ngClass]="{'active': currentSection === 'marketPlace'}">Market Place</button>

        <h6 class="mb-2">PROFILE</h6>

        <button (click)="changeSection('profile')" [ngClass]="{'active': currentSection === 'profile'}">Profile</button>
        <br>
        <button  (click)="changeSection('trackLibrary')" [ngClass]="{'active': currentSection === 'trackLibrary'}">Mis mp3</button>
        <br>
        <button (click)="changeSection('purchases')" [ngClass]="{'active': currentSection === 'purchases'}">Mis compras</button>
        <br>
        <button  (click)="changeSection('history')" [ngClass]="{'active': currentSection === 'history'}">Historial</button>

        <h6 class="mb-2">MAS...</h6>

        <button [routerLink]="['/resources']" (click)="changeSection('resources')" [ngClass]="{'active': currentSection === 'resources'}">Resources</button>
        <br>
        <button [routerLink]="['/configuration']" (click)="changeSection('configuration')" [ngClass]="{'active': currentSection === 'configuration'}">Configuracion</button>
        <br>
        <button [routerLink]="['/support']" (click)="changeSection('support')" [ngClass]="{'active': currentSection === 'support'}">Support</button>
        <br>
        <button (click)="logout()" [ngClass]="{'active': currentSection === 'logout'}">Cerrar Sesión</button>
      </div>
      <ul class="flex space-x-4">
        <li><img class="h-12" src="assets/dashboard/youtubeLogo.webp" alt="youtube"></li>
        <li><img class="h-12" src="assets/dashboard/instagramLogo.webp" alt="instagram"></li>
        <li><img class="h-12" src="assets/dashboard/discordLogo.webp" alt="discord"></li>
        <li><img class="h-12" src="assets/dashboard/beatstarsLogo.webp" alt="beatStars"></li>
      </ul>
      
      

      <div class="hypeSoundsText text-white">
        <p>© 2023 Hype Sounds.</p>
        <p>All rights reserved.</p>
      </div>
      
</div>

</nav>
